branch: 'master'
schema: 'myschema.graphql'
notifications:
  slack: https://hooks.slack.com/services/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

diff:
  annotations: false
  failOnBreaking: false
