branch: 'master'
schema: 'myschema.graphql'
notifications:
  slack: https://hooks.slack.com/services/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

diff:
  annotations: false
  failOnBreaking: false
