branch: 'master'
schema: 'myschema.graphql'
notifications:
  slack: https://hooks.slack.com/services/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

# Customizing Schema Diff
diff:
  # Pull Request annotations (enabled by default)
  annotations: false
  # Fail on breaking changes or force SUCCESS when disabled (enabled by default)
  failOnBreaking: false
  # Label to mark Pull Request introducing breaking changes as safe and expected ('approved-breaking-change' by default)
  approveLabel: 'approved-breaking-change'
