branch: 'master'
schema: 'myschema.graphql'
notifications:
  slack: ${{ secrets.GRAPHQL_SLACK_WEBHOOK }}

# Customizing Schema Diff
diff:
  # Pull Request annotations (enabled by default)
  annotations: false
