branch: 'master'
schema: 'myschema.graphql'


env:
  dev:
    branch: 'master'
    notifications:
      slack: ${{ secrets.GRAPHQL_SLACK_WEBHOOK }}

diff:
  annotations: false
  failOnBreaking: false
